// packages/svelte-querybuilder/src/components/ActionElement.svelte
<script lang="ts">
  import type { ActionElementProps } from '../types';
  import { clsx } from '@react-querybuilder/core';

  let {
    className,
    handleOnClick,
    label,
    title,
    disabled = false,
    testID,
    level,
    path,
    ...otherProps
  }: ActionElementProps = $props();

  function onClick(e: MouseEvent) {
    if (!disabled && handleOnClick) {
      handleOnClick(e);
    }
  }
</script>

<button
  type="button"
  class={clsx(className, { disabled })}
  title={title}
  disabled={disabled}
  data-testid={testID}
  data-level={level}
  data-path={JSON.stringify(path)}
  onclick={onClick}
  {...otherProps}
>
  {label}
</button>

// packages/react-querybuilder/src/controls/ActionElement.tsx
import type { ActionProps } from '../types';

const ActionElement = ({
  className,
  handleOnClick,
  label,
  title,
  disabled,
  testID,
}: ActionProps) => (
  <button
    data-testid={testID}
    disabled={disabled}
    className={className}
    title={title}
    onClick={e => handleOnClick(e)}>
    {label}
  </button>
);

ActionElement.displayName = 'ActionElement';

export default ActionElement;
