// packages/svelte-querybuilder/src/components/ValueSelector.svelte
<script lang="ts">
  import type { ValueSelectorProps } from '../types';
  import { clsx, isOptionGroupArray } from '@react-querybuilder/core';

  let {
    className,
    handleOnChange,
    options,
    value,
    title,
    disabled = false,
    multiple = false,
    listsAsArrays = false,
    testID,
    level,
    path,
    ...otherProps
  }: ValueSelectorProps = $props();

  const isGrouped = $derived(isOptionGroupArray(options));

  function onChange(e: Event) {
    const target = e.target as HTMLSelectElement;
    if (!disabled && handleOnChange) {
      if (multiple) {
        const selected = Array.from(target.selectedOptions).map(opt => opt.value);
        handleOnChange(listsAsArrays ? selected : selected.join(','));
      } else {
        handleOnChange(target.value);
      }
    }
  }

  // Compute selected values for multiselect
  const selectedValues = $derived(
    multiple && typeof value === 'string' 
      ? value.split(',').map(v => v.trim()) 
      : multiple && Array.isArray(value)
        ? value
        : []
  );
</script>

<select
  class={clsx(className, { disabled })}
  title={title}
  disabled={disabled}
  multiple={multiple}
  data-testid={testID}
  data-level={level}
  data-path={JSON.stringify(path)}
  onchange={onChange}
  {...otherProps}
>
  {#if isGrouped}
    {#each options as group}
      <optgroup label={group.label}>
        {#each group.options as option}
          <option
            value={option.name}
            disabled={option.disabled}
            selected={multiple ? selectedValues.includes(option.name) : value === option.name}
          >
            {option.label}
          </option>
        {/each}
      </optgroup>
    {/each}
  {:else}
    {#each options as option}
      <option
        value={option.name}
        disabled={option.disabled}
        selected={multiple ? selectedValues.includes(option.name) : value === option.name}
      >
        {option.label}
      </option>
    {/each}
  {/if}
</select>

// packages/react-querybuilder/src/controls/ValueSelector.tsx
import { useMemo, type ChangeEvent } from 'react';
import type { ValueSelectorProps } from '../types';
import { toArray, toOptions } from '../utils';

export const ValueSelector = ({
  className,
  handleOnChange,
  options,
  title,
  value,
  multiple,
  listsAsArrays,
  disabled,
  testID,
}: ValueSelectorProps) => {
  const onChange = useMemo(
    () =>
      multiple
        ? (e: ChangeEvent<HTMLSelectElement>) => {
            const valArray = Array.from(e.target.selectedOptions).map(o => o.value);
            handleOnChange(listsAsArrays ? valArray : valArray.join(','));
          }
        : (e: ChangeEvent<HTMLSelectElement>) => handleOnChange(e.target.value),
    [handleOnChange, listsAsArrays, multiple]
  );

  return (
    <select
      data-testid={testID}
      className={className}
      value={multiple ? toArray(value) : value}
      title={title}
      disabled={disabled}
      multiple={!!multiple}
      onChange={onChange}>
      {toOptions(options)}
    </select>
  );
};

ValueSelector.displayName = 'ValueSelector';
