// packages/svelte-querybuilder/src/components/NotToggle.svelte
<script lang="ts">
  import type { NotToggleProps } from '../types';
  import { clsx } from '@react-querybuilder/core';

  let {
    className,
    handleOnChange,
    label,
    title,
    checked = false,
    disabled = false,
    testID,
    level,
    path,
    ...otherProps
  }: NotToggleProps = $props();

  function onChange(e: Event) {
    const target = e.target as HTMLInputElement;
    if (!disabled && handleOnChange) {
      handleOnChange(target.checked);
    }
  }
</script>

<label
  class={clsx(className, { disabled })}
  title={title}
  data-testid={testID}
  data-level={level}
  data-path={JSON.stringify(path)}
>
  <input
    type="checkbox"
    checked={checked}
    disabled={disabled}
    onchange={onChange}
    {...otherProps}
  />
  {label}
</label>

// src/controls/NotToggle.tsx
import type { NotToggleProps } from '../types';

const NotToggle = ({ className, handleOnChange, title, label, checked }: NotToggleProps) => (
  <label className={className} title={title}>
    <input type="checkbox" onChange={(e) => handleOnChange(e.target.checked)} checked={!!checked} />
    {label}
  </label>
);

NotToggle.displayName = 'NotToggle';

export default NotToggle;
