// packages/svelte-querybuilder/src/components/RuleGroup.svelte
<script lang="ts">
  import type { RuleGroupProps } from '../types';
  import { clsx, isRuleGroup } from '@react-querybuilder/core';
  import Rule from './Rule.svelte';
  import Self from './RuleGroup.svelte';

  let {
    ruleGroup,
    path,
    schema,
    actions,
    level = 0,
    disabled = false,
    shiftUpDisabled = false,
    shiftDownDisabled = false,
    context
  }: RuleGroupProps = $props();

  const testID = $derived(`ruleGroup-${path.join('-')}`);
  const isDisabled = $derived(disabled || ruleGroup.disabled);
  const isMuted = $derived(ruleGroup.muted);

  const groupClassName = $derived(
    clsx(
      schema.classNames.ruleGroup,
      isDisabled && schema.classNames.disabled,
      isMuted && schema.classNames.muted
    )
  );

  function handleCombinatorChange(newCombinator: string) {
    actions.onPropChange('combinator', newCombinator, path);
  }

  function handleNotToggleChange(checked: boolean) {
    actions.onPropChange('not', checked, path);
  }

  function handleAddRule() {
    actions.onRuleAdd(path);
  }

  function handleAddGroup() {
    actions.onGroupAdd(path);
  }

  function handleRemove() {
    if (level > 0) {
      actions.onGroupRemove(path);
    }
  }

  function handleClone() {
    const parentPath = path.slice(0, -1);
    const clonedGroup = JSON.parse(JSON.stringify(ruleGroup));
    actions.onGroupAdd(parentPath);
  }

  function handleLock() {
    actions.onPropChange('disabled', !ruleGroup.disabled, path);
  }

  function handleMute() {
    actions.onPropChange('muted', !ruleGroup.muted, path);
  }

  function handleShiftUp() {
    if (level === 0) return;
    const parentPath = path.slice(0, -1);
    const index = path[path.length - 1];
    if (index > 0) {
      const newPath = [...parentPath, index - 1];
      actions.moveRule(path, newPath);
    }
  }

  function handleShiftDown() {
    if (level === 0) return;
    const parentPath = path.slice(0, -1);
    const index = path[path.length - 1];
    const newPath = [...parentPath, index + 1];
    actions.moveRule(path, newPath);
  }

  const CombinatorSelector = $derived(schema.controls.combinatorSelector);
  const NotToggle = $derived(schema.controls.notToggle);
  const ActionElement = $derived(schema.controls.actionElement);
  const ShiftActions = $derived(schema.controls.shiftActions);
</script>

<div
  class={groupClassName}
  data-testid={testID}
  data-level={level}
  data-path={JSON.stringify(path)}
  data-rule-group-id={ruleGroup.id}
>
  <!-- Header -->
  <div class={schema.classNames.header}>
    <div>
      <!-- Combinator Selector -->
      <CombinatorSelector
        options={schema.combinators}
        value={ruleGroup.combinator}
        handleOnChange={handleCombinatorChange}
        disabled={isDisabled}
        className={schema.classNames.combinators}
        testID={`${testID}-combinator`}
        level={level}
        path={path}
        schema={schema}
        context={context}
      />

      <!-- NOT Toggle -->
      {#if schema.showNotToggle}
        <NotToggle
          checked={!!ruleGroup.not}
          handleOnChange={handleNotToggleChange}
          disabled={isDisabled}
          label={schema.translations.notToggle?.label ?? 'NOT'}
          title={schema.translations.notToggle?.title ?? 'Invert this group'}
          className={schema.classNames.notToggle}
          testID={`${testID}-not`}
          level={level}
          path={path}
          schema={schema}
          context={context}
        />
      {/if}

      <!-- Group Actions -->
        <ActionElement
          label={schema.translations.addRule?.label ?? '+ Rule'}
          title={schema.translations.addRule?.title ?? 'Add rule'}
          handleOnClick={handleAddRule}
          disabled={isDisabled}
          className={schema.classNames.addRule}
          testID={`${testID}-addRule`}
          level={level}
          path={path}
          schema={schema}
          context={context}
          ruleOrGroup={ruleGroup}
        />

        <ActionElement
          label={schema.translations.addGroup?.label ?? '+ Group'}
          title={schema.translations.addGroup?.title ?? 'Add group'}
          handleOnClick={handleAddGroup}
          disabled={isDisabled}
          className={schema.classNames.addGroup}
          testID={`${testID}-addGroup`}
          level={level}
          path={path}
          schema={schema}
          context={context}
          ruleOrGroup={ruleGroup}
        />

        {#if schema.showCloneButtons && level > 0}
          <ActionElement
            label={schema.translations.cloneRuleGroup?.label ?? '⧉'}
            title={schema.translations.cloneRuleGroup?.title ?? 'Clone group'}
            handleOnClick={handleClone}
            disabled={isDisabled}
            className={schema.classNames.cloneGroup}
            testID={`${testID}-clone`}
            level={level}
            path={path}
            schema={schema}
            context={context}
            ruleOrGroup={ruleGroup}
          />
        {/if}

        {#if schema.showLockButtons}
          <ActionElement
            label={ruleGroup.disabled ? (schema.translations.lockGroupDisabled?.label ?? '🔒') : (schema.translations.lockGroup?.label ?? '🔓')}
            title={ruleGroup.disabled ? (schema.translations.lockGroupDisabled?.title ?? 'Unlock group') : (schema.translations.lockGroup?.title ?? 'Lock group')}
            handleOnClick={handleLock}
            disabled={false}
            className={schema.classNames.lockGroup}
            testID={`${testID}-lock`}
            level={level}
            path={path}
            schema={schema}
            context={context}
            ruleOrGroup={ruleGroup}
          />
        {/if}

        {#if schema.showMuteButtons}
          <ActionElement
            label={ruleGroup.muted ? (schema.translations.unmuteGroup?.label ?? '🔊') : (schema.translations.muteGroup?.label ?? '🔇')}
            title={ruleGroup.muted ? (schema.translations.unmuteGroup?.title ?? 'Unmute group') : (schema.translations.muteGroup?.title ?? 'Mute group')}
            handleOnClick={handleMute}
            disabled={isDisabled}
            className={schema.classNames.muteGroup}
            testID={`${testID}-mute`}
            level={level}
            path={path}
            schema={schema}
            context={context}
            ruleOrGroup={ruleGroup}
          />
        {/if}

        {#if level > 0}
          <ActionElement
            label={schema.translations.removeGroup?.label ?? '✕'}
            title={schema.translations.removeGroup?.title ?? 'Remove group'}
            handleOnClick={handleRemove}
            disabled={isDisabled}
            className={schema.classNames.removeGroup}
            testID={`${testID}-remove`}
            level={level}
            path={path}
            schema={schema}
            context={context}
            ruleOrGroup={ruleGroup}
          />
        {/if}

        {#if schema.showShiftActions && level > 0}
          <ShiftActions
            shiftUp={handleShiftUp}
            shiftDown={handleShiftDown}
            shiftUpDisabled={shiftUpDisabled}
            shiftDownDisabled={shiftDownDisabled}
            disabled={isDisabled}
            className={schema.classNames.shiftActions}
            testID={`${testID}-shift`}
            level={level}
            path={path}
            schema={schema}
            context={context}
          />
        {/if}
    </div>
  </div>

  <!-- Body -->
  <div class={schema.classNames.body}>
    {#each ruleGroup.rules as ruleOrGroup, index}
      {@const rulePath = [...path, index]}
      {@const childShiftUpDisabled = index === 0}
      {@const childShiftDownDisabled = path.length === 0 && index === ruleGroup.rules.length - 1}
      
      {#if schema.showCombinatorsBetweenRules && index > 0}
        <div class={schema.classNames.betweenRules}>
          <CombinatorSelector
            options={schema.combinators}
            value={ruleGroup.combinator}
            handleOnChange={handleCombinatorChange}
            disabled={isDisabled}
            className={clsx(schema.classNames.combinators, schema.classNames.betweenRules)}
            testID={`${testID}-inlineCombinator-${index}`}
            level={level}
            path={path}
            schema={schema}
            context={context}
          />
        </div>
      {/if}

      {#if isRuleGroup(ruleOrGroup)}
        <Self
          ruleGroup={ruleOrGroup}
          path={rulePath}
          schema={schema}
          actions={actions}
          level={level + 1}
          disabled={isDisabled}
          shiftUpDisabled={childShiftUpDisabled}
          shiftDownDisabled={childShiftDownDisabled}
          context={context}
        />
      {:else}
        <Rule
          rule={ruleOrGroup}
          path={rulePath}
          schema={schema}
          actions={actions}
          level={level + 1}
          disabled={isDisabled}
          shiftUpDisabled={childShiftUpDisabled}
          shiftDownDisabled={childShiftDownDisabled}
          context={context}
        />
      {/if}
    {/each}
  </div>
</div>

// packages/react-querybuilder/src/components/RuleGroup.tsx
import * as React from 'react';
import { Fragment } from 'react';
import { TestID } from '../defaults';
import { useRuleGroup, useStopEventPropagation } from '../hooks';
import type { RuleGroupArray, RuleGroupICArray, RuleGroupProps } from '../types';
import { isRuleGroup, isRuleGroupType } from '../utils';

/**
 * Default component to display {@link RuleGroupType} and {@link RuleGroupTypeIC}
 * objects. This is actually a small wrapper around {@link RuleGroupHeaderComponents}
 * and {@link RuleGroupBodyComponents}.
 */
export const RuleGroup = React.memo((props: RuleGroupProps) => {
  const rg = { ...props, ...useRuleGroup(props) };

  rg.addRule = useStopEventPropagation(rg.addRule);
  rg.addGroup = useStopEventPropagation(rg.addGroup);
  rg.cloneGroup = useStopEventPropagation(rg.cloneGroup);
  rg.toggleLockGroup = useStopEventPropagation(rg.toggleLockGroup);
  rg.removeGroup = useStopEventPropagation(rg.removeGroup);

  return (
    <div
      ref={rg.previewRef}
      title={rg.accessibleDescription}
      className={rg.outerClassName}
      data-testid={TestID.ruleGroup}
      data-dragmonitorid={rg.dragMonitorId}
      data-dropmonitorid={rg.dropMonitorId}
      data-rule-group-id={rg.id}
      data-level={rg.path.length}
      data-path={JSON.stringify(rg.path)}>
      <div ref={rg.dropRef} className={rg.classNames.header}>
        <RuleGroupHeaderComponents {...(rg as Parameters<typeof RuleGroupHeaderComponents>[0])} />
      </div>
      <div className={rg.classNames.body}>
        <RuleGroupBodyComponents {...(rg as Parameters<typeof RuleGroupBodyComponents>[0])} />
      </div>
    </div>
  );
});

RuleGroup.displayName = 'RuleGroup';

/**
 * Renders a `React.Fragment` containing an array of form controls for managing
 * a {@link RuleGroupType} or {@link RuleGroupTypeIC}.
 */
export const RuleGroupHeaderComponents = React.memo(
  (rg: RuleGroupProps & ReturnType<typeof useRuleGroup>) => {
    const {
      schema: {
        controls: {
          shiftActions: ShiftActionsControlElement,
          dragHandle: DragHandleControlElement,
          combinatorSelector: CombinatorSelectorControlElement,
          notToggle: NotToggleControlElement,
          addRuleAction: AddRuleActionControlElement,
          addGroupAction: AddGroupActionControlElement,
          cloneGroupAction: CloneGroupActionControlElement,
          lockGroupAction: LockGroupActionControlElement,
          removeGroupAction: RemoveGroupActionControlElement,
        },
      },
    } = rg;

    return (
      <>
        {rg.path.length > 0 && rg.schema.showShiftActions && (
          <ShiftActionsControlElement
            testID={TestID.shiftActions}
            level={rg.path.length}
            path={rg.path}
            titles={{
              shiftUp: rg.translations.shiftActionUp.title,
              shiftDown: rg.translations.shiftActionDown.title,
            }}
            labels={{
              shiftUp: rg.translations.shiftActionUp.label,
              shiftDown: rg.translations.shiftActionDown.label,
            }}
            className={rg.classNames.shiftActions}
            disabled={rg.disabled}
            context={rg.context}
            validation={rg.validationResult}
            schema={rg.schema}
            ruleOrGroup={rg.ruleGroup}
            lastInGroup={rg.lastInGroup}
          />
        )}
        {rg.path.length > 0 && rg.schema.enableDragAndDrop && (
          <DragHandleControlElement
            testID={TestID.dragHandle}
            ref={rg.dragRef}
            level={rg.path.length}
            path={rg.path}
            title={rg.translations.dragHandle.title}
            label={rg.translations.dragHandle.label}
            className={rg.classNames.dragHandle}
            disabled={rg.disabled}
            context={rg.context}
            validation={rg.validationResult}
            schema={rg.schema}
            ruleOrGroup={rg.ruleGroup}
          />
        )}
        {!rg.schema.showCombinatorsBetweenRules && !rg.schema.independentCombinators && (
          <CombinatorSelectorControlElement
            testID={TestID.combinators}
            options={rg.schema.combinators}
            value={rg.combinator}
            title={rg.translations.combinators.title}
            className={rg.classNames.combinators}
            handleOnChange={rg.onCombinatorChange}
            rules={rg.ruleGroup.rules}
            level={rg.path.length}
            path={rg.path}
            disabled={rg.disabled}
            context={rg.context}
            validation={rg.validationResult}
            schema={rg.schema}
          />
        )}
        {rg.schema.showNotToggle && (
          <NotToggleControlElement
            testID={TestID.notToggle}
            className={rg.classNames.notToggle}
            title={rg.translations.notToggle.title}
            label={rg.translations.notToggle.label}
            checked={rg.ruleGroup.not}
            handleOnChange={rg.onNotToggleChange}
            level={rg.path.length}
            disabled={rg.disabled}
            path={rg.path}
            context={rg.context}
            validation={rg.validationResult}
            schema={rg.schema}
            ruleGroup={rg.ruleGroup}
          />
        )}
        <AddRuleActionControlElement
          testID={TestID.addRule}
          label={rg.translations.addRule.label}
          title={rg.translations.addRule.title}
          className={rg.classNames.addRule}
          handleOnClick={rg.addRule}
          rules={rg.ruleGroup.rules}
          level={rg.path.length}
          path={rg.path}
          disabled={rg.disabled}
          context={rg.context}
          validation={rg.validationResult}
          ruleOrGroup={rg.ruleGroup}
          schema={rg.schema}
        />
        <AddGroupActionControlElement
          testID={TestID.addGroup}
          label={rg.translations.addGroup.label}
          title={rg.translations.addGroup.title}
          className={rg.classNames.addGroup}
          handleOnClick={rg.addGroup}
          rules={rg.ruleGroup.rules}
          level={rg.path.length}
          path={rg.path}
          disabled={rg.disabled}
          context={rg.context}
          validation={rg.validationResult}
          ruleOrGroup={rg.ruleGroup}
          schema={rg.schema}
        />
        {rg.schema.showCloneButtons && rg.path.length >= 1 && (
          <CloneGroupActionControlElement
            testID={TestID.cloneGroup}
            label={rg.translations.cloneRuleGroup.label}
            title={rg.translations.cloneRuleGroup.title}
            className={rg.classNames.cloneGroup}
            handleOnClick={rg.cloneGroup}
            rules={rg.ruleGroup.rules}
            level={rg.path.length}
            path={rg.path}
            disabled={rg.disabled}
            context={rg.context}
            validation={rg.validationResult}
            ruleOrGroup={rg.ruleGroup}
            schema={rg.schema}
          />
        )}
        {rg.schema.showLockButtons && (
          <LockGroupActionControlElement
            testID={TestID.lockGroup}
            label={rg.translations.lockGroup.label}
            title={rg.translations.lockGroup.title}
            className={rg.classNames.lockGroup}
            handleOnClick={rg.toggleLockGroup}
            rules={rg.ruleGroup.rules}
            level={rg.path.length}
            path={rg.path}
            disabled={rg.disabled}
            disabledTranslation={rg.parentDisabled ? undefined : rg.translations.lockGroupDisabled}
            context={rg.context}
            validation={rg.validationResult}
            ruleOrGroup={rg.ruleGroup}
            schema={rg.schema}
          />
        )}
        {rg.path.length > 0 && (
          <RemoveGroupActionControlElement
            testID={TestID.removeGroup}
            label={rg.translations.removeGroup.label}
            title={rg.translations.removeGroup.title}
            className={rg.classNames.removeGroup}
            handleOnClick={rg.removeGroup}
            rules={rg.ruleGroup.rules}
            level={rg.path.length}
            path={rg.path}
            disabled={rg.disabled}
            context={rg.context}
            validation={rg.validationResult}
            ruleOrGroup={rg.ruleGroup}
            schema={rg.schema}
          />
        )}
      </>
    );
  }
);

/**
 * Renders a `React.Fragment` containing an array of either (1) {@link Rule} and
 * {@link RuleGroup}, or (2) {@link Rule}, {@link RuleGroup}, and {@link InlineCombinator}.
 */
export const RuleGroupBodyComponents = React.memo(
  (rg: RuleGroupProps & ReturnType<typeof useRuleGroup>) => {
    const {
      schema: {
        controls: {
          combinatorSelector: CombinatorSelectorControlElement,
          inlineCombinator: InlineCombinatorControlElement,
          ruleGroup: RuleGroupControlElement,
          rule: RuleControlElement,
        },
      },
    } = rg;

    return (
      <>
        {(rg.ruleGroup.rules as RuleGroupICArray | RuleGroupArray).map(
          (r, idx, { length: ruleArrayLength }) => {
            const thisPathMemo = rg.pathsMemo[idx];
            const thisPath = thisPathMemo.path;
            const thisPathDisabled = thisPathMemo.disabled || (typeof r !== 'string' && r.disabled);
            const lastInGroup = idx === ruleArrayLength - 1;
            const key = typeof r === 'string' ? [...thisPath, r].join('-') : r.id;
            return (
              <Fragment key={key}>
                {idx > 0 &&
                  !rg.schema.independentCombinators &&
                  rg.schema.showCombinatorsBetweenRules && (
                    <InlineCombinatorControlElement
                      options={rg.schema.combinators}
                      value={rg.combinator}
                      title={rg.translations.combinators.title}
                      className={rg.classNames.combinators}
                      handleOnChange={rg.onCombinatorChange}
                      rules={rg.ruleGroup.rules}
                      level={rg.path.length}
                      context={rg.context}
                      validation={rg.validationResult}
                      component={CombinatorSelectorControlElement}
                      path={thisPath}
                      disabled={rg.disabled}
                      independentCombinators={rg.schema.independentCombinators}
                      schema={rg.schema}
                    />
                  )}
                {typeof r === 'string' ? (
                  <InlineCombinatorControlElement
                    options={rg.schema.combinators}
                    value={r}
                    title={rg.translations.combinators.title}
                    className={rg.classNames.combinators}
                    handleOnChange={val => rg.onIndependentCombinatorChange(val, idx)}
                    rules={rg.ruleGroup.rules}
                    level={rg.path.length}
                    context={rg.context}
                    validation={rg.validationResult}
                    component={CombinatorSelectorControlElement}
                    path={thisPath}
                    disabled={thisPathDisabled}
                    independentCombinators={rg.schema.independentCombinators}
                    schema={rg.schema}
                  />
                ) : isRuleGroup(r) ? (
                  <RuleGroupControlElement
                    id={r.id}
                    schema={rg.schema}
                    actions={rg.actions}
                    path={thisPath}
                    translations={rg.translations}
                    ruleGroup={r}
                    rules={r.rules}
                    combinator={isRuleGroupType(r) ? r.combinator : undefined}
                    not={!!r.not}
                    disabled={thisPathDisabled}
                    parentDisabled={rg.parentDisabled || rg.disabled}
                    context={rg.context}
                    lastInGroup={lastInGroup}
                  />
                ) : (
                  <RuleControlElement
                    id={r.id!}
                    rule={r}
                    field={r.field}
                    operator={r.operator}
                    value={r.value}
                    valueSource={r.valueSource}
                    schema={rg.schema}
                    actions={rg.actions}
                    path={thisPath}
                    disabled={thisPathDisabled}
                    parentDisabled={rg.parentDisabled || rg.disabled}
                    translations={rg.translations}
                    context={rg.context}
                    lastInGroup={lastInGroup}
                  />
                )}
              </Fragment>
            );
          }
        )}
      </>
    );
  }
);
