// packages/react-querybuilder/src/components/ActionElement.tsx
import * as React from 'react';
import type { ActionProps } from '../types';

/**
 * Default `<button>` component used by {@link QueryBuilder}.
 */
export const ActionElement = (props: ActionProps) => (
  <button
    type="button"
    data-testid={props.testID}
    disabled={props.disabled && !props.disabledTranslation}
    className={props.className}
    title={
      props.disabledTranslation && props.disabled ? props.disabledTranslation.title : props.title
    }
    onClick={e => props.handleOnClick(e)}>
    {props.disabledTranslation && props.disabled ? props.disabledTranslation.label : props.label}
  </button>
);

// packages/svelte-querybuilder/src/components/ActionElement.svelte
<script lang="ts">
  import type { ActionElementProps } from '../types';
  import { clsx } from '@react-querybuilder/core';

  let {
    className,
    handleOnClick,
    label,
    title,
    disabled = false,
    testID,
    level,
    path,
    ...otherProps
  }: ActionElementProps = $props();

  function onClick(e: MouseEvent) {
    if (!disabled && handleOnClick) {
      handleOnClick(e);
    }
  }
</script>

<button
  type="button"
  class={clsx(className, { disabled })}
  title={title}
  disabled={disabled}
  data-testid={testID}
  data-level={level}
  data-path={JSON.stringify(path)}
  onclick={onClick}
  {...otherProps}
>
  {label}
</button>
