// packages/react-querybuilder/src/RuleGroup.tsx
import type { RuleGroupProps } from '@react-querybuilder/ts';
import {
  defaultCombinators,
  getParentPath,
  getValidationClassNames,
  pathsAreEqual,
  standardClassnames,
  TestID,
} from '@react-querybuilder/util';
import { clsx } from 'clsx';
import type { MouseEvent as ReactMouseEvent } from 'react';
import { Fragment, useMemo } from 'react';
import { useDeprecatedProps, useReactDndWarning } from './hooks';

export const RuleGroup = ({
  id,
  path,
  ruleGroup,
  translations,
  schema,
  actions,
  disabled: disabledProp,
  parentDisabled,
  context,
  combinator: combinatorProp,
  rules: rulesProp,
  not: notProp,
  // Drag-and-drop
  dragMonitorId = '',
  dropMonitorId = '',
  previewRef = null,
  dragRef = null,
  dropRef = null,
}: RuleGroupProps) => {
  const {
    classNames,
    combinators,
    controls: {
      dragHandle: DragHandleControlElement,
      combinatorSelector: CombinatorSelectorControlElement,
      inlineCombinator: InlineCombinatorControlElement,
      notToggle: NotToggleControlElement,
      addRuleAction: AddRuleActionControlElement,
      addGroupAction: AddGroupActionControlElement,
      cloneGroupAction: CloneGroupActionControlElement,
      lockGroupAction: LockGroupActionControlElement,
      removeGroupAction: RemoveGroupActionControlElement,
      ruleGroup: RuleGroupControlElement,
      rule: RuleControlElement,
    },
    createRule,
    createRuleGroup,
    independentCombinators,
    showCombinatorsBetweenRules,
    showNotToggle,
    showCloneButtons,
    showLockButtons,
    validationMap,
    disabledPaths,
    enableDragAndDrop,
  } = schema;
  const { onGroupAdd, onGroupRemove, onPropChange, onRuleAdd, moveRule } = actions;
  const disabled = !!parentDisabled || !!disabledProp;

  const { rules, not } = ruleGroup ? ruleGroup : { rules: rulesProp, not: notProp };
  let combinator: string = defaultCombinators[0].name;
  if (ruleGroup && 'combinator' in ruleGroup) {
    combinator = ruleGroup.combinator;
  } else if (!ruleGroup) {
    combinator = combinatorProp ?? combinator;
  }

  useDeprecatedProps('ruleGroup', !!ruleGroup);

  const classNamesMemo = useMemo(
    () => ({
      header: clsx(standardClassnames.header, classNames.header),
      dragHandle: clsx(standardClassnames.dragHandle, classNames.dragHandle),
      combinators: clsx(standardClassnames.combinators, classNames.combinators),
      notToggle: clsx(standardClassnames.notToggle, classNames.notToggle),
      addRule: clsx(standardClassnames.addRule, classNames.addRule),
      addGroup: clsx(standardClassnames.addGroup, classNames.addGroup),
      cloneGroup: clsx(standardClassnames.cloneGroup, classNames.cloneGroup),
      lockGroup: clsx(standardClassnames.lockGroup, classNames.lockGroup),
      removeGroup: clsx(standardClassnames.removeGroup, classNames.removeGroup),
      body: clsx(standardClassnames.body, classNames.body),
    }),
    [classNames]
  );

  useReactDndWarning(
    enableDragAndDrop,
    !!(dragMonitorId || dropMonitorId || previewRef || dragRef || dropRef)
  );

  const onCombinatorChange = (value: any) => {
    if (!disabled) {
      onPropChange('combinator', value, path);
    }
  };

  const onIndependentCombinatorChange = (value: any, index: number) => {
    if (!disabled) {
      onPropChange('combinator', value, path.concat([index]));
    }
  };

  const onNotToggleChange = (checked: boolean) => {
    if (!disabled) {
      onPropChange('not', checked, path);
    }
  };

  const addRule = (event: ReactMouseEvent, context?: any) => {
    event.preventDefault();
    event.stopPropagation();

    if (!disabled) {
      const newRule = createRule();
      onRuleAdd(newRule, path, context);
    }
  };

  const addGroup = (event: ReactMouseEvent, context?: any) => {
    event.preventDefault();
    event.stopPropagation();

    if (!disabled) {
      const newGroup = createRuleGroup();
      onGroupAdd(newGroup, path, context);
    }
  };

  const cloneGroup = (event: ReactMouseEvent) => {
    event.preventDefault();
    event.stopPropagation();

    if (!disabled) {
      const newPath = [...getParentPath(path), path[path.length - 1] + 1];
      moveRule(path, newPath, true);
    }
  };

  const toggleLockGroup = (event: ReactMouseEvent) => {
    event.preventDefault();
    event.stopPropagation();

    onPropChange('disabled', !disabled, path);
  };

  const removeGroup = (event: ReactMouseEvent) => {
    event.preventDefault();
    event.stopPropagation();

    if (!disabled) {
      onGroupRemove(path);
    }
  };

  const level = path.length;

  const validationResult = validationMap[id ?? /* istanbul ignore next */ ''];
  const validationClassName = getValidationClassNames(validationResult);
  const outerClassName = clsx(
    standardClassnames.ruleGroup,
    classNames.ruleGroup,
    { [standardClassnames.disabled]: disabled },
    validationClassName
  );

  return (
    <div
      ref={previewRef}
      className={outerClassName}
      data-testid={TestID.ruleGroup}
      data-dragmonitorid={dragMonitorId}
      data-dropmonitorid={dropMonitorId}
      data-rule-group-id={id}
      data-level={level}
      data-path={JSON.stringify(path)}>
      <div ref={dropRef} className={classNamesMemo.header}>
        {level > 0 && (
          <DragHandleControlElement
            testID={TestID.dragHandle}
            ref={dragRef}
            level={level}
            path={path}
            title={translations.dragHandle.title}
            label={translations.dragHandle.label}
            className={classNamesMemo.dragHandle}
            disabled={disabled}
            context={context}
            validation={validationResult}
          />
        )}
        {!showCombinatorsBetweenRules && !independentCombinators && (
          <CombinatorSelectorControlElement
            testID={TestID.combinators}
            options={combinators}
            value={combinator}
            title={translations.combinators.title}
            className={classNamesMemo.combinators}
            handleOnChange={onCombinatorChange}
            rules={rules}
            level={level}
            path={path}
            disabled={disabled}
            context={context}
            validation={validationResult}
          />
        )}
        {showNotToggle && (
          <NotToggleControlElement
            testID={TestID.notToggle}
            className={classNamesMemo.notToggle}
            title={translations.notToggle.title}
            label={translations.notToggle.label}
            checked={not}
            handleOnChange={onNotToggleChange}
            level={level}
            disabled={disabled}
            path={path}
            context={context}
            validation={validationResult}
          />
        )}
        <AddRuleActionControlElement
          testID={TestID.addRule}
          label={translations.addRule.label}
          title={translations.addRule.title}
          className={classNamesMemo.addRule}
          handleOnClick={addRule}
          rules={rules}
          level={level}
          path={path}
          disabled={disabled}
          context={context}
          validation={validationResult}
        />
        <AddGroupActionControlElement
          testID={TestID.addGroup}
          label={translations.addGroup.label}
          title={translations.addGroup.title}
          className={classNamesMemo.addGroup}
          handleOnClick={addGroup}
          rules={rules}
          level={level}
          path={path}
          disabled={disabled}
          context={context}
          validation={validationResult}
        />
        {showCloneButtons && path.length >= 1 && (
          <CloneGroupActionControlElement
            testID={TestID.cloneGroup}
            label={translations.cloneRuleGroup.label}
            title={translations.cloneRuleGroup.title}
            className={classNamesMemo.cloneGroup}
            handleOnClick={cloneGroup}
            rules={rules}
            level={level}
            path={path}
            disabled={disabled}
            context={context}
            validation={validationResult}
          />
        )}
        {showLockButtons && (
          <LockGroupActionControlElement
            testID={TestID.lockGroup}
            label={translations.lockGroup.label}
            title={translations.lockGroup.title}
            className={classNamesMemo.lockGroup}
            handleOnClick={toggleLockGroup}
            rules={rules}
            level={level}
            path={path}
            disabled={disabled}
            disabledTranslation={parentDisabled ? undefined : translations.lockGroupDisabled}
            context={context}
            validation={validationResult}
          />
        )}
        {path.length >= 1 && (
          <RemoveGroupActionControlElement
            testID={TestID.removeGroup}
            label={translations.removeGroup.label}
            title={translations.removeGroup.title}
            className={classNamesMemo.removeGroup}
            handleOnClick={removeGroup}
            rules={rules}
            level={level}
            path={path}
            disabled={disabled}
            context={context}
            validation={validationResult}
          />
        )}
      </div>
      <div className={classNamesMemo.body}>
        {rules.map((r, idx) => {
          const thisPath = [...path, idx];
          const thisPathDisabled =
            disabled ||
            (typeof r !== 'string' && r.disabled) ||
            disabledPaths.some(p => pathsAreEqual(thisPath, p));
          const key = typeof r === 'string' ? [...thisPath, r].join('-') : r.id;
          return (
            <Fragment key={key}>
              {idx > 0 && !independentCombinators && showCombinatorsBetweenRules && (
                <InlineCombinatorControlElement
                  options={combinators}
                  value={combinator}
                  title={translations.combinators.title}
                  className={classNamesMemo.combinators}
                  handleOnChange={onCombinatorChange}
                  rules={rules}
                  level={level}
                  context={context}
                  validation={validationResult}
                  component={CombinatorSelectorControlElement}
                  path={thisPath}
                  disabled={thisPathDisabled}
                  independentCombinators={independentCombinators}
                />
              )}
              {typeof r === 'string' ? (
                <InlineCombinatorControlElement
                  options={combinators}
                  value={r}
                  title={translations.combinators.title}
                  className={classNamesMemo.combinators}
                  handleOnChange={val => onIndependentCombinatorChange(val, idx)}
                  rules={rules}
                  level={level}
                  context={context}
                  validation={validationResult}
                  component={CombinatorSelectorControlElement}
                  path={thisPath}
                  disabled={thisPathDisabled}
                  independentCombinators={independentCombinators}
                />
              ) : 'rules' in r ? (
                <RuleGroupControlElement
                  id={r.id}
                  schema={schema}
                  actions={actions}
                  path={thisPath}
                  translations={translations}
                  ruleGroup={r}
                  rules={r.rules}
                  combinator={'combinator' in r ? r.combinator : undefined}
                  not={!!r.not}
                  disabled={thisPathDisabled}
                  parentDisabled={parentDisabled || disabled}
                  context={context}
                />
              ) : (
                <RuleControlElement
                  id={r.id!}
                  rule={r}
                  field={r.field}
                  operator={r.operator}
                  value={r.value}
                  valueSource={r.valueSource}
                  schema={schema}
                  actions={actions}
                  path={thisPath}
                  disabled={thisPathDisabled}
                  parentDisabled={parentDisabled || disabled}
                  translations={translations}
                  context={context}
                />
              )}
            </Fragment>
          );
        })}
      </div>
    </div>
  );
};

RuleGroup.displayName = 'RuleGroup';

// packages/svelte-querybuilder/src/components/RuleGroup.svelte
<script lang="ts">
  import type { RuleGroupProps } from '../types';
  import { clsx, isRuleGroup } from '@react-querybuilder/core';
  import Rule from './Rule.svelte';
  import Self from './RuleGroup.svelte';

  let {
    ruleGroup,
    path,
    schema,
    actions,
    level = 0,
    disabled = false,
    shiftUpDisabled = false,
    shiftDownDisabled = false,
    context
  }: RuleGroupProps = $props();

  const testID = $derived(`ruleGroup-${path.join('-')}`);
  const isDisabled = $derived(disabled || ruleGroup.disabled);
  const isMuted = $derived(ruleGroup.muted);

  const groupClassName = $derived(
    clsx(
      schema.classNames.ruleGroup,
      isDisabled && schema.classNames.disabled,
      isMuted && schema.classNames.muted
    )
  );

  function handleCombinatorChange(newCombinator: string) {
    actions.onPropChange('combinator', newCombinator, path);
  }

  function handleNotToggleChange(checked: boolean) {
    actions.onPropChange('not', checked, path);
  }

  function handleAddRule() {
    actions.onRuleAdd(path);
  }

  function handleAddGroup() {
    actions.onGroupAdd(path);
  }

  function handleRemove() {
    if (level > 0) {
      actions.onGroupRemove(path);
    }
  }

  function handleClone() {
    const parentPath = path.slice(0, -1);
    const clonedGroup = JSON.parse(JSON.stringify(ruleGroup));
    actions.onGroupAdd(parentPath);
  }

  function handleLock() {
    actions.onPropChange('disabled', !ruleGroup.disabled, path);
  }

  function handleMute() {
    actions.onPropChange('muted', !ruleGroup.muted, path);
  }

  function handleShiftUp() {
    if (level === 0) return;
    const parentPath = path.slice(0, -1);
    const index = path[path.length - 1];
    if (index > 0) {
      const newPath = [...parentPath, index - 1];
      actions.moveRule(path, newPath);
    }
  }

  function handleShiftDown() {
    if (level === 0) return;
    const parentPath = path.slice(0, -1);
    const index = path[path.length - 1];
    const newPath = [...parentPath, index + 1];
    actions.moveRule(path, newPath);
  }

  const CombinatorSelector = $derived(schema.controls.combinatorSelector);
  const NotToggle = $derived(schema.controls.notToggle);
  const ActionElement = $derived(schema.controls.actionElement);
  const ShiftActions = $derived(schema.controls.shiftActions);
</script>

<div
  class={groupClassName}
  data-testid={testID}
  data-level={level}
  data-path={JSON.stringify(path)}
  data-rule-group-id={ruleGroup.id}
>
  <!-- Header -->
  <div class={schema.classNames.header}>
    <div>
      <!-- Combinator Selector -->
      <CombinatorSelector
        options={schema.combinators}
        value={ruleGroup.combinator}
        handleOnChange={handleCombinatorChange}
        disabled={isDisabled}
        className={schema.classNames.combinators}
        testID={`${testID}-combinator`}
        level={level}
        path={path}
        schema={schema}
        context={context}
      />

      <!-- NOT Toggle -->
      {#if schema.showNotToggle}
        <NotToggle
          checked={!!ruleGroup.not}
          handleOnChange={handleNotToggleChange}
          disabled={isDisabled}
          label={schema.translations.notToggle?.label ?? 'NOT'}
          title={schema.translations.notToggle?.title ?? 'Invert this group'}
          className={schema.classNames.notToggle}
          testID={`${testID}-not`}
          level={level}
          path={path}
          schema={schema}
          context={context}
        />
      {/if}

      <!-- Group Actions -->
        <ActionElement
          label={schema.translations.addRule?.label ?? '+ Rule'}
          title={schema.translations.addRule?.title ?? 'Add rule'}
          handleOnClick={handleAddRule}
          disabled={isDisabled}
          className={schema.classNames.addRule}
          testID={`${testID}-addRule`}
          level={level}
          path={path}
          schema={schema}
          context={context}
          ruleOrGroup={ruleGroup}
        />

        <ActionElement
          label={schema.translations.addGroup?.label ?? '+ Group'}
          title={schema.translations.addGroup?.title ?? 'Add group'}
          handleOnClick={handleAddGroup}
          disabled={isDisabled}
          className={schema.classNames.addGroup}
          testID={`${testID}-addGroup`}
          level={level}
          path={path}
          schema={schema}
          context={context}
          ruleOrGroup={ruleGroup}
        />

        {#if schema.showCloneButtons && level > 0}
          <ActionElement
            label={schema.translations.cloneRuleGroup?.label ?? '⧉'}
            title={schema.translations.cloneRuleGroup?.title ?? 'Clone group'}
            handleOnClick={handleClone}
            disabled={isDisabled}
            className={schema.classNames.cloneGroup}
            testID={`${testID}-clone`}
            level={level}
            path={path}
            schema={schema}
            context={context}
            ruleOrGroup={ruleGroup}
          />
        {/if}

        {#if schema.showLockButtons}
          <ActionElement
            label={ruleGroup.disabled ? (schema.translations.lockGroupDisabled?.label ?? '🔒') : (schema.translations.lockGroup?.label ?? '🔓')}
            title={ruleGroup.disabled ? (schema.translations.lockGroupDisabled?.title ?? 'Unlock group') : (schema.translations.lockGroup?.title ?? 'Lock group')}
            handleOnClick={handleLock}
            disabled={false}
            className={schema.classNames.lockGroup}
            testID={`${testID}-lock`}
            level={level}
            path={path}
            schema={schema}
            context={context}
            ruleOrGroup={ruleGroup}
          />
        {/if}

        {#if schema.showMuteButtons}
          <ActionElement
            label={ruleGroup.muted ? (schema.translations.unmuteGroup?.label ?? '🔊') : (schema.translations.muteGroup?.label ?? '🔇')}
            title={ruleGroup.muted ? (schema.translations.unmuteGroup?.title ?? 'Unmute group') : (schema.translations.muteGroup?.title ?? 'Mute group')}
            handleOnClick={handleMute}
            disabled={isDisabled}
            className={schema.classNames.muteGroup}
            testID={`${testID}-mute`}
            level={level}
            path={path}
            schema={schema}
            context={context}
            ruleOrGroup={ruleGroup}
          />
        {/if}

        {#if level > 0}
          <ActionElement
            label={schema.translations.removeGroup?.label ?? '✕'}
            title={schema.translations.removeGroup?.title ?? 'Remove group'}
            handleOnClick={handleRemove}
            disabled={isDisabled}
            className={schema.classNames.removeGroup}
            testID={`${testID}-remove`}
            level={level}
            path={path}
            schema={schema}
            context={context}
            ruleOrGroup={ruleGroup}
          />
        {/if}

        {#if schema.showShiftActions && level > 0}
          <ShiftActions
            shiftUp={handleShiftUp}
            shiftDown={handleShiftDown}
            shiftUpDisabled={shiftUpDisabled}
            shiftDownDisabled={shiftDownDisabled}
            disabled={isDisabled}
            className={schema.classNames.shiftActions}
            testID={`${testID}-shift`}
            level={level}
            path={path}
            schema={schema}
            context={context}
          />
        {/if}
    </div>
  </div>

  <!-- Body -->
  <div class={schema.classNames.body}>
    {#each ruleGroup.rules as ruleOrGroup, index}
      {@const rulePath = [...path, index]}
      {@const childShiftUpDisabled = index === 0}
      {@const childShiftDownDisabled = path.length === 0 && index === ruleGroup.rules.length - 1}
      
      {#if schema.showCombinatorsBetweenRules && index > 0}
        <div class={schema.classNames.betweenRules}>
          <CombinatorSelector
            options={schema.combinators}
            value={ruleGroup.combinator}
            handleOnChange={handleCombinatorChange}
            disabled={isDisabled}
            className={clsx(schema.classNames.combinators, schema.classNames.betweenRules)}
            testID={`${testID}-inlineCombinator-${index}`}
            level={level}
            path={path}
            schema={schema}
            context={context}
          />
        </div>
      {/if}

      {#if isRuleGroup(ruleOrGroup)}
        <Self
          ruleGroup={ruleOrGroup}
          path={rulePath}
          schema={schema}
          actions={actions}
          level={level + 1}
          disabled={isDisabled}
          shiftUpDisabled={childShiftUpDisabled}
          shiftDownDisabled={childShiftDownDisabled}
          context={context}
        />
      {:else}
        <Rule
          rule={ruleOrGroup}
          path={rulePath}
          schema={schema}
          actions={actions}
          level={level + 1}
          disabled={isDisabled}
          shiftUpDisabled={childShiftUpDisabled}
          shiftDownDisabled={childShiftDownDisabled}
          context={context}
        />
      {/if}
    {/each}
  </div>
</div>
